from pathlib import Path

import pytest

from replay import run

REPO_ROOT = Path(__file__).resolve().parents[3]
FIXTURE = REPO_ROOT / "data" / "replay" / "fixture.jsonl"
DEFAULT_FLOORS = REPO_ROOT / "skills" / "fraud-replay" / "floors.yaml"


@pytest.fixture(autouse=True)
def _ensure_fixture_exists():
    # The fixture is generated by `make fixture`. Build it lazily if missing
    # so the test suite is self-contained.
    if not FIXTURE.exists():
        import subprocess
        subprocess.check_call(["python3", str(REPO_ROOT / "data" / "replay" / "build_fixture.py")])


def test_replay_passes_floors_on_seed_fixture(tmp_path):
    result = run(replay_path=FIXTURE, floors_path=DEFAULT_FLOORS, report_dir=tmp_path)
    assert result["status"] == "ok"
    assert result["failed_schemes"] == []
    for sid, recall in result["schemes"].items():
        assert recall >= 0.5, f"{sid} recall {recall} below sanity floor"


def test_replay_writes_json_and_md_reports(tmp_path):
    run(replay_path=FIXTURE, floors_path=DEFAULT_FLOORS, report_dir=tmp_path)
    assert (tmp_path / "replay_report.json").exists()
    assert (tmp_path / "replay_report.md").exists()


def test_replay_fails_when_floors_unreachable(tmp_path):
    impossible_floors = tmp_path / "floors.yaml"
    impossible_floors.write_text(
        "card_testing_burst_v1: 1.5\n"  # > 1.0 is unreachable
    )
    result = run(replay_path=FIXTURE, floors_path=impossible_floors, report_dir=tmp_path)
    assert result["status"] == "fail"
    assert "card_testing_burst_v1" in result["failed_schemes"]
