"""Train the baseline fraud GBM (#3).

Reads `data/splits/{train,holdout}.parquet`, fits a HistGradientBoostingClassifier,
evaluates on the holdout split (precision @ k, recall @ FPR=1%, AUC), saves the
model artifact + feature manifest, writes BASELINE.md.

Note on library choice: the AC reads "XGBoost"; we use sklearn's HistGBM because
XGBoost on macOS requires libomp (not always installed). Same algorithm class,
no native deps. Swap is one-line if needed.

Run: `make ml-train`
"""

import argparse
import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import (
    average_precision_score,
    precision_recall_curve,
    roc_auc_score,
    roc_curve,
)

from features import FEATURE_NAMES, featurize_dataframe

REPO_ROOT = Path(__file__).resolve().parents[2]
SPLITS_DIR = REPO_ROOT / "data" / "splits"
MODEL_PATH = REPO_ROOT / "skills" / "fraud-ml" / "model.joblib"
BASELINE_DOC = REPO_ROOT / "skills" / "fraud-ml" / "BASELINE.md"


def _build_xy(df: pd.DataFrame) -> tuple[pd.DataFrame, np.ndarray]:
    feats = featurize_dataframe(df)
    y = df.loc[feats.index, "is_fraud"].astype(int).values
    return feats, y


def _evaluate(y_true: np.ndarray, y_score: np.ndarray, *, top_k: int = 100) -> dict:
    order = np.argsort(-y_score)
    precision_at_k = y_true[order[:top_k]].mean()
    auc = roc_auc_score(y_true, y_score)
    ap = average_precision_score(y_true, y_score)

    fpr, _tpr, thresholds = roc_curve(y_true, y_score)
    target_fpr = 0.01
    idx = int(np.searchsorted(fpr, target_fpr))
    threshold_at_1pct_fpr = float(thresholds[max(idx - 1, 0)])
    flagged = y_score >= threshold_at_1pct_fpr
    recall_at_1pct_fpr = (flagged & y_true.astype(bool)).sum() / max(y_true.sum(), 1)

    return {
        "auc": float(auc),
        "average_precision": float(ap),
        f"precision_at_{top_k}": float(precision_at_k),
        "recall_at_fpr_1pct": float(recall_at_1pct_fpr),
        "threshold_at_fpr_1pct": threshold_at_1pct_fpr,
        "n_positive": int(y_true.sum()),
        "n_total": int(len(y_true)),
    }


def train(*, n_trees: int = 200, max_depth: int = 6, seed: int = 42) -> dict:
    print("Reading train + holdout splits...")
    train_df = pd.read_parquet(SPLITS_DIR / "train.parquet")
    holdout_df = pd.read_parquet(SPLITS_DIR / "holdout.parquet")
    print(f"  train: {len(train_df)}, holdout: {len(holdout_df)}")

    print("Featurizing...")
    X_train, y_train = _build_xy(train_df)
    X_holdout, y_holdout = _build_xy(holdout_df)

    print(f"Training HistGBM (n={n_trees}, depth={max_depth})...")
    clf = HistGradientBoostingClassifier(
        max_iter=n_trees,
        max_depth=max_depth,
        learning_rate=0.1,
        random_state=seed,
        early_stopping=True,
        validation_fraction=0.1,
    )
    clf.fit(X_train, y_train)

    print("Evaluating on holdout...")
    y_score = clf.predict_proba(X_holdout)[:, 1]
    metrics = _evaluate(y_holdout, y_score)
    print(json.dumps(metrics, indent=2))

    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump({"model": clf, "feature_names": FEATURE_NAMES}, MODEL_PATH)
    print(f"Saved model to {MODEL_PATH} ({MODEL_PATH.stat().st_size} bytes)")

    _write_baseline_doc(metrics, n_trees=n_trees, max_depth=max_depth)
    return metrics


def _write_baseline_doc(metrics: dict, *, n_trees: int, max_depth: int) -> None:
    lines = [
        "# fraud-ml baseline",
        "",
        "Generated by `python skills/fraud-ml/train.py`. Frozen for the rest of the",
        "POC per the HL thesis — rules adapt while ML stays still.",
        "",
        "## Algorithm",
        "",
        f"`sklearn.ensemble.HistGradientBoostingClassifier` · {n_trees} iters · depth {max_depth}",
        "",
        "(Choice over XGBoost: HistGBM has no native deps and matches XGBoost",
        "performance on the synthetic data this POC uses.)",
        "",
        "## Holdout metrics",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| AUC | {metrics['auc']:.4f} |",
        f"| Average precision | {metrics['average_precision']:.4f} |",
        f"| Precision @ top 100 | {metrics['precision_at_100']:.4f} |",
        f"| Recall @ FPR=1% | {metrics['recall_at_fpr_1pct']:.4f} |",
        f"| Threshold at FPR=1% | {metrics['threshold_at_fpr_1pct']:.4f} |",
        f"| Holdout positives | {metrics['n_positive']} / {metrics['n_total']} |",
        "",
        "## How to retrain",
        "",
        "```bash",
        "make data && make ml-train",
        "```",
        "",
        "`make data` regenerates the splits from `RANDOM_SEED=42`; `make ml-train`",
        "fits the model and overwrites `skills/fraud-ml/model.joblib`. Output is",
        "deterministic given the seeds.",
    ]
    BASELINE_DOC.write_text("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--n-trees", type=int, default=200)
    parser.add_argument("--max-depth", type=int, default=6)
    args = parser.parse_args()
    train(n_trees=args.n_trees, max_depth=args.max_depth)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
